services:
  - type: web
    name: agente-ia-vendas
    runtime: python3.11
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run st_app.py --server.port $PORT --server.address 0.0.0.0